AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Serverless GitHub app

Parameters:
  githubAppId:
    Description: The App ID of your GitHub app
    Type: String
    Default: ${ secrets.AWS_GHAPP_ID }
  githubWebhookSecret:
    Description: The webhook secret of your GitHub app
    Type: String
    Default: ${ secrets.AWS_GHAPP_WEBHOOK_SECRET}
  githubPrivateKey:
    Description: The private key of your GitHub app
    Type: String
    Default: ${ secrets.AWS_GHAPP_PRIVATE_KEY }

#  --config-env githubAppId=${{ secrets.AWS_GHAPP_ID }},githubWebhookSecret=${{ secrets.AWS_GHAPP_WEBHOOK_SECRET}},githubPrivateKey=${{ secrets.AWS_GHAPP_PRIVATE_KEY }}  
# --parameter-overrides githubAppId=${{ secrets.AWS_GHAPP_ID }},githubWebhookSecret=${{ secrets.AWS_GHAPP_WEBHOOK_SECRET}},githubPrivateKey=${{ secrets.AWS_GHAPP_PRIVATE_KEY }} -

Resources:
  webhooks:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: ghrunner-app
      Description: Basic Auth Funtion
      CodeUri: .
      Handler: handler.webhooks
      Runtime: nodejs16.x
      MemorySize: 256
      Timeout: 20
      PackageType: Zip
      Tags:
        map-migrated: d-server-01068mdjl5jze3
      Events:
        ApiEvent:
          Type: HttpApi
          Properties:
            Path: /ghrunner-app
            Method: post
      Environment:
        Variables:
          APP_ID: !Ref githubAppId
          WEBHOOK_SECRET: !ref githubWebhookSecret
          PRIVATE_KEY: !Ref githubPrivateKey