---
name: Create Lambda

on:
  workflow_run:
    workflows: ["Create Role"]
    types:
      - completed
jobs:
  release:
    runs-on: ubuntu-latest
    environment: deployment
    name: Create the AWS Function
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ssh-key: ${{ secrets.DEPLOY_KEY }}

      - name: A
        if: ${{ github.event.workflow_run.conclusion == 'failure' }}
          run: |
            echo "The function already exists. EXIT 0"
            exit 0

      - name: Install node 16
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: npm

      - name: Configure git
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
      - name: Configure aws
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install project modules
        run: npm ci --production

      - name: Create lambda archive
        run: zip -r function.zip .

      - name: Get the arn of the role and then create the function
        run: |
         ARN_ROLE=$(aws iam get-role --role-name ${{ secrets.AWS_FUNCTION_ROLE }} --query "Role.Arn" --output text)
         aws lambda create-function --function-name ${{ secrets.LAMBDA_FUNCTION }} \
         --zip-file fileb://function.zip \
         --handler handler.webhooks \
         --runtime nodejs16.x \
         --role $ARN_ROLE \
         --environment "Variables={APP_ID=${{ secrets.AWS_GHAPP_ID}},PRIVATE_KEY=${{ secrets.AWS_GHAPP_PRIVATE_KEY }},WEBHOOK_SECRET=${{ secrets.AWS_GHAPP_WEBHOOK_SECRET }}}"
      
      - name: Wait for function to be created
        run: aws lambda wait function-exists --function-name ${{ secrets.LAMBDA_FUNCTION }}

      - name: Get the arn of the created function and create the api for the trigger
        run: |
            arn=$(aws lambda get-function --function-name ${{ secrets.LAMBDA_FUNCTION }} --query "Configuration.FunctionArn" --output text)
            aws apigatewayv2 create-api --name ${{ secrets.AWS_API_NAME}} --protocol-type HTTP --target $arn
    

