name: Deploy the lambda using AWS SAM
"on":
  push:
    branches:
      - aws-sam
  workflow_dispatch: {}
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
      - run: npm ci
      - uses: aws-actions/setup-sam@v2
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - run: sam build webhooks
      - run: >
         sam deploy sam deploy --stack-name ${{ secrets.AWS_STACK_NAME }} \
          --resolve-s3 \
          --capabilities CAPABILITY_IAM \
          --parameter-overrides 'awsRole="${{ secrets.AWS_ARN_ROLE }}" \
          githubAppId="${{ secrets.AWS_GHAPP_ID }}" \
          githubWebhookSecret="${{ secrets.AWS_GHAPP_WEBHOOK_SECRET }}" \
          githubPrivateKey="${{ secrets.AWS_GHAPP_PRIVATE_KEY }}" \
          githubOwner="${{ secrets.OWNER }}" \
          githubRepository="${{ secrets.REPOSITORY }}" \
          githubWorkflowName="${{ secrets.WORKFLOW_FILE_NAME }}" \
          githubBranch="${{ secrets.BRANCH }}" \
          githubJobFilter="${{ secrets.JOB_FILTER }}"' \
          --no-confirm-changeset