name: Deploy the lambda using AWS Sam
"on":
  push:
    branches:
      - aws-sam
  workflow_dispatch: {}
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: npm
      - run: npm ci
      - uses: aws-actions/setup-sam@v2
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - run: sam build
      - run: --stack-name sam-app --s3-bucket aws-us-east-1-310989808867-dummy-lambda-pipe --capabilities CAPABILITY_IAM --no-confirm-changeset --no-fail-on-empty-changeset 